version: '3' # Версия спецификации docker-compose

services: # Раздел описания сервисов
  front: # Описываем сервис нашего веб-приложения
    container_name: front-udw-avia-dev # Наименование контейнера приложения
    build:
      context: . # Папка, где находится Dockerfile, из которого будет создан контейнер
    volumes:
      - front-static-dev: /usr/share/nginx/html  # Вынесение статики в отдельный том
    env_file:
      - .env # Указание файла с переменными окружения
    ports:
      - 8080:80
    networks:
      - udw-avia-dev # Подключение контейнера к общей сети udw-avia-dev
    # создание и накатывание миграций, сбор статики и запуск сервера разработки
#    command: bash -c "python manage.py makemigrations &&
#      python manage.py migrate &&
#      python manage.py collectstatic --noinput &&
#      gunicorn config.wsgi:application --bind 0.0.0.0:8000"

volumes: # Раздел с томами, используемыми в сервисах
  front-static-dev:
  postgres-data-dev:

networks: # Раздел с сетями, используемыми в сервисах
  udw-avia-dev:
    driver: bridge
